"use client";

import { useState } from "react";
import { api } from "@/lib/api-client";
import { aggregateCashWeek, calculateSalary, calcCashProgress, cashWeekStart, dailyCashTarget, generateWeekdayTargets } from "@/lib/cash";
import { toDDMMYYYY, dowName } from "@/lib/date";
import { fmt } from "@/lib/format";
import type { AppState } from "@/lib/types";
import { AmountInput, CancelLink, DescInput, ErrText, FieldLabel, SaveButton, Sheet, SheetHint, SheetTitle } from "./Sheet";
import type { Refresh, ShowToast } from "./AppShell";

export default function CashTab({ state, refresh, showToast }: { state: AppState; refresh: Refresh; showToast: ShowToast }) {
  const today = toDDMMYYYY(new Date());
  const monday = cashWeekStart(today);
  const [adding, setAdding] = useState(false);
  const [editing, setEditing] = useState(false);
  const week = aggregateCashWeek(state.cashEntries, monday);
  const settings = state.cashSettings;
  const salary = calculateSalary({ weeklyCash: week.weeklyTotal, ...settings });
  const salaryAtTarget = calculateSalary({ weeklyCash: settings.weeklyTarget, ...settings });
  const progress = calcCashProgress({ weeklyCash: week.weeklyTotal, weeklyTarget: settings.weeklyTarget, salary, salaryTarget: salaryAtTarget });
  const todayAmount = week.days.find((day) => day.date === today)?.amount || 0;
  const todayTarget = dailyCashTarget(settings.weekdayTargets, today);

  return <main className="max-w-[520px] mx-auto px-4 pb-24 pt-5">
    <div className="flex justify-between items-start"><div><h1 className="font-display text-2xl font-bold m-0">Касса</h1><p className="text-sm m-0" style={{ color: "var(--muted)" }}>{today} · {dowName(today)}</p></div><button onClick={() => setEditing(true)} className="rounded-xl px-3 py-2 text-sm border" style={{ borderColor: "var(--border)", color: "var(--muted)" }}>Изменить цель</button></div>
    <section className="grid grid-cols-2 gap-3 mt-5"><Metric label="Касса за сегодня" value={`${fmt(todayAmount)} / ${fmt(todayTarget)}`} /><Metric label="Касса за неделю" value={`${fmt(week.weeklyTotal)} / ${fmt(settings.weeklyTarget)}`} /></section>
    <section className="mt-4 rounded-2xl p-4" style={{ background: "var(--hover)", border: "1px solid var(--border)" }}><div className="font-semibold">Выполнение кассы · {progress.cashPercent}%</div><Bar percent={progress.cashPercent} /><div className="font-semibold mt-4">Прогресс к зарплате · {progress.salaryPercent}%</div><div className="text-sm" style={{ color: "var(--muted)" }}>{fmt(salary)} из {fmt(salaryAtTarget)}</div><Bar percent={progress.salaryPercent} /></section>
    <div className="grid grid-cols-5 gap-2 mt-4">{week.days.map((day) => { const target = dailyCashTarget(settings.weekdayTargets, day.date); const percent = target ? Math.min(100, Math.round(day.amount / target * 100)) : 0; return <div key={day.date} className="rounded-xl p-2 text-center" style={{ background: day.date === today ? "var(--accent-blue)" : "var(--hover)", color: day.date === today ? "#fff" : "inherit" }}><div className="text-xs font-semibold">{dowName(day.date)}</div><div className="text-xs mt-2">{percent}%</div><div className="text-[10px]">{fmt(day.amount)}</div><div className="text-[10px] opacity-70">/ {fmt(target)}</div></div>; })}</div>
    <button onClick={() => setAdding(true)} className="mt-5 w-full py-4 rounded-2xl border-none font-bold" style={{ background: "var(--accent-blue)", color: "#fff" }}>+ Добавить кассу</button>
    <CashAdd show={adding} onClose={() => setAdding(false)} refresh={refresh} showToast={showToast} date={today} />
    <CashSettingsDialog key={editing ? "open" : "closed"} show={editing} onClose={() => setEditing(false)} settings={settings} refresh={refresh} />
  </main>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl p-4" style={{ background: "var(--hover)", border: "1px solid var(--border)" }}><div className="text-xs" style={{ color: "var(--muted)" }}>{label}</div><div className="font-bold text-sm mt-1">{value}</div></div>; }
function Bar({ percent }: { percent: number }) { return <div className="h-2 rounded-full mt-2 overflow-hidden" style={{ background: "var(--line)" }}><div className="h-full rounded-full" style={{ width: `${percent}%`, background: "var(--accent-blue)" }} /></div>; }
function CashAdd({ show, onClose, refresh, showToast, date }: { show: boolean; onClose: () => void; refresh: Refresh; showToast: ShowToast; date: string }) { const [amount, setAmount] = useState(""); const [error, setError] = useState(""); async function save() { const value = Number(amount); if (!value || value <= 0) return setError("Укажи сумму больше нуля"); try { await api.addCash({ date, amount: value }); await refresh(); onClose(); showToast(`Касса добавлена: ${fmt(value)}`); } catch (e) { setError(e instanceof Error ? e.message : "Не удалось сохранить"); } } return <Sheet show={show} onClose={onClose}><SheetTitle>Добавить кассу</SheetTitle><SheetHint>Каждое сохранение добавляет новую сумму к дню {date}.</SheetHint><AmountInput value={amount} onChange={(e) => setAmount(e.target.value)} /><ErrText>{error}</ErrText><SaveButton onClick={save}>Добавить</SaveButton><CancelLink onClick={onClose}>Отмена</CancelLink></Sheet>; }
function CashSettingsDialog({ show, onClose, settings, refresh }: { show: boolean; onClose: () => void; settings: AppState["cashSettings"]; refresh: Refresh }) { const [weekly, setWeekly] = useState(String(settings.weeklyTarget)); const [targets, setTargets] = useState(settings.weekdayTargets); const [failedPlan, setFailedPlan] = useState(settings.failedPlan); const [opsTotal, setOpsTotal] = useState(String(settings.opsTotal)); const [opsPlan, setOpsPlan] = useState(String(settings.opsPlan)); const [managersTotal, setManagersTotal] = useState(String(settings.managersTotal)); const [managersPlan, setManagersPlan] = useState(String(settings.managersPlan)); const [error, setError] = useState(""); const setWeeklyAndGenerate=(value:string)=>{setWeekly(value); setTargets(generateWeekdayTargets(Number(value)||0));}; async function save(){const input={weeklyTarget:Number(weekly)||0,weekdayTargets:targets,failedPlan,opsTotal:Number(opsTotal)||0,opsPlan:Number(opsPlan)||0,managersTotal:Number(managersTotal)||0,managersPlan:Number(managersPlan)||0}; if(input.opsPlan>input.opsTotal||input.managersPlan>input.managersTotal)return setError("Выполнено не может быть больше общего"); try{await api.updateCashSettings(input); await refresh(); onClose();}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить");}} const labels:{key:keyof typeof targets;label:string}[]=[{key:"mon",label:"Пн"},{key:"tue",label:"Вт"},{key:"wed",label:"Ср"},{key:"thu",label:"Чт"},{key:"fri",label:"Пт"}]; return <Sheet show={show} onClose={onClose}><SheetTitle>Изменить цель</SheetTitle><FieldLabel>Цель на неделю, ₽</FieldLabel><DescInput type="number" value={weekly} onChange={e=>setWeeklyAndGenerate(e.target.value)} /><SheetHint>Дни можно настроить отдельно.</SheetHint>{labels.map(({key,label})=><div key={key}><FieldLabel>{label}, ₽</FieldLabel><DescInput type="number" value={String(targets[key])} onChange={e=>setTargets({...targets,[key]:Number(e.target.value)||0})}/></div>)}<FieldLabel>Мотивация</FieldLabel><label className="text-sm block mb-2"><input type="checkbox" checked={failedPlan} onChange={e=>setFailedPlan(e.target.checked)}/> План провален</label><div className="grid grid-cols-2 gap-2"><DescInput type="number" placeholder="Операторы всего" value={opsTotal} onChange={e=>setOpsTotal(e.target.value)}/><DescInput type="number" placeholder="Операторы вып." value={opsPlan} onChange={e=>setOpsPlan(e.target.value)}/><DescInput type="number" placeholder="Менеджеры всего" value={managersTotal} onChange={e=>setManagersTotal(e.target.value)}/><DescInput type="number" placeholder="Менеджеры вып." value={managersPlan} onChange={e=>setManagersPlan(e.target.value)}/></div><ErrText>{error}</ErrText><SaveButton onClick={save}>Сохранить</SaveButton><CancelLink onClick={onClose}>Отмена</CancelLink></Sheet>; }
