"use client";
import { useState } from "react";
import { api } from "@/lib/api-client";
import { aggregateCashWeek, calculateSalary, cashScenarioOptions, cashWeekStart, dailyCashTarget, generateRemainingWeekdayTargets } from "@/lib/cash";
import { toDDMMYYYY, dowName } from "@/lib/date";
import { fmt } from "@/lib/format";
import type { AppState, CashEntry } from "@/lib/types";
import { AmountInput, CancelLink, DescInput, ErrText, FieldLabel, SaveButton, Sheet, SheetHint, SheetTitle } from "./Sheet";
import type { Refresh, ShowToast } from "./AppShell";

export default function CashTab({ state, refresh, showToast }: { state: AppState; refresh: Refresh; showToast: ShowToast }) {
  const today = toDDMMYYYY(new Date()); const settings = state.cashSettings; const week = aggregateCashWeek(state.cashEntries, cashWeekStart(today));
  const [entry, setEntry] = useState<CashEntry | null | undefined>(undefined); const [settingsOpen, setSettingsOpen] = useState(false);
  const scenarios = cashScenarioOptions({ today, goal: state.goal, envelopes: state.envelopes, salary: settings, multipliers: settings.scenarioMultipliers });
  async function choose(weeklyTarget: number) {
    await api.updateCashSettings({ ...settings, weeklyTarget, weekdayTargets: generateRemainingWeekdayTargets(weeklyTarget, today) }); await refresh(); showToast(`Цель кассы: ${fmt(weeklyTarget)} в неделю`);
  }
  return <main className="max-w-[520px] mx-auto px-4 pb-24 pt-5"><div className="flex justify-between"><div><h1 className="font-display text-2xl font-bold m-0">Касса / Доход</h1><p className="text-sm m-0" style={{color:"var(--muted)"}}>{today} · {dowName(today)}</p></div><button onClick={()=>setSettingsOpen(true)}>Настройки</button></div>
    <section className="grid grid-cols-2 gap-3 mt-5">{week.days.map(day=><button key={day.date} onClick={()=>setEntry({ id:"", date:day.date, amount:0 })} className="rounded-xl p-3 text-left" style={{background:"var(--hover)",border:"1px solid var(--border)"}}><b>{dowName(day.date)}</b><br/>{fmt(day.amount)} / {fmt(dailyCashTarget(settings.weekdayTargets,day.date))}</button>)}</section>
    <div className="mt-4 rounded-2xl p-4" style={{background:"var(--hover)",border:"1px solid var(--border)"}}>Касса недели: <b>{fmt(week.weeklyTotal)} / {fmt(settings.weeklyTarget)}</b><br/><span style={{color:"var(--muted)"}}>Оценка зарплаты: {fmt(calculateSalary({weeklyCash:week.weeklyTotal,...settings}))}</span></div>
    <h2 className="text-base mt-6">Сценарии цели</h2><p className="text-xs" style={{color:"var(--muted)"}}>Регулярные конверты и взнос в цель покрываются расчётом зарплаты. Проценты сценариев редактируются в настройках.</p>
    <div className="grid gap-3">{scenarios.map(option=><button key={option.name} onClick={()=>choose(option.weeklyCash)} className="rounded-2xl p-4 text-left" style={{background:"var(--hover)",border:"1px solid var(--border)"}}><b>{option.name} · {Math.round(option.multiplier*100)}%</b><div className="font-display text-xl">{fmt(option.weeklyCash)} / нед.</div><small>Минимум {fmt(option.minimumWeeklyCash)} · завершение {option.completionDate || "—"}</small></button>)}</div>
    <h2 className="text-base mt-6">Записи кассы</h2>{state.cashEntries.slice().reverse().map(item=><button key={item.id} onClick={()=>setEntry(item)} className="w-full flex justify-between py-2 text-left bg-transparent" style={{borderBottom:"1px solid var(--line)"}}><span>{item.date}</span><b>{fmt(item.amount)} · изменить</b></button>)}
    <button onClick={()=>setEntry({id:"",date:today,amount:0})} className="mt-5 w-full py-4 rounded-2xl border-none font-bold" style={{background:"var(--accent-blue)",color:"#fff"}}>+ Добавить кассу</button>
    <CashEntrySheet entry={entry} close={()=>setEntry(undefined)} refresh={refresh} showToast={showToast}/><SettingsSheet show={settingsOpen} close={()=>setSettingsOpen(false)} settings={settings} refresh={refresh}/></main>;
}
function CashEntrySheet({entry,close,refresh,showToast}:{entry:CashEntry|null|undefined;close:()=>void;refresh:Refresh;showToast:ShowToast}) { const [amount,setAmount]=useState(String(entry?.amount||"")); const [date,setDate]=useState(entry?.date||""); const [error,setError]=useState(""); async function save(){const value=Number(amount);if(!date||value<=0)return setError("Укажи дату и сумму больше нуля");try{if(entry?.id)await api.updateCash(entry.id,{date,amount:value});else await api.addCash({date,amount:value});await refresh();showToast("Касса сохранена");close()}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить")}} return <Sheet show={!!entry} onClose={close}><SheetTitle>{entry?.id?"Изменить кассу":"Добавить кассу"}</SheetTitle><FieldLabel>Дата (ДД.ММ.ГГГГ)</FieldLabel><DescInput value={date} onChange={e=>setDate(e.target.value)}/><FieldLabel>Сумма</FieldLabel><AmountInput value={amount} onChange={e=>setAmount(e.target.value)}/><ErrText>{error}</ErrText><SaveButton onClick={save}>Сохранить</SaveButton>{entry?.id&&<button onClick={async()=>{await api.deleteCash(entry.id);await refresh();showToast("Запись удалена");close()}} className="w-full mt-3 text-red-500">Удалить</button>}<CancelLink onClick={close}>Отмена</CancelLink></Sheet> }
function SettingsSheet({show,close,settings,refresh}:{show:boolean;close:()=>void;settings:AppState["cashSettings"];refresh:Refresh}) { const [values,setValues]=useState(settings.scenarioMultipliers.map(v=>String(v*100))); async function save(){await api.updateCashSettings({...settings,scenarioMultipliers:values.map(v=>Math.max(0,Number(v)||0)/100) as [number,number,number]});await refresh();close()} return <Sheet show={show} onClose={close}><SheetTitle>Настройки сценариев</SheetTitle><SheetHint>Процент от рассчитанного минимального недельного CASH.</SheetHint>{["Минималка","Средний","Герой-красавчик"].map((label,i)=><div key={label}><FieldLabel>{label}, %</FieldLabel><DescInput type="number" value={values[i]} onChange={e=>setValues(values.map((v,n)=>n===i?e.target.value:v))}/></div>)}<SaveButton onClick={save}>Сохранить</SaveButton><CancelLink onClick={close}>Отмена</CancelLink></Sheet> }
