"use client";
import { useState } from "react";
import { api } from "@/lib/api-client";
import { toDDMMYYYY } from "@/lib/date";
import { fmt } from "@/lib/format";
import type { AppState } from "@/lib/types";
import EnvelopesTab from "./EnvelopesTab";
import type { Refresh, ShowToast } from "./AppShell";

export default function ExpenseTab({state,refresh,showToast}:{state:AppState;refresh:Refresh;showToast:ShowToast}) { const [amount,setAmount]=useState(""); const [desc,setDesc]=useState(""); const [error,setError]=useState(""); const spent=state.transactions.filter(t=>t.amount<0).reduce((sum,t)=>sum+Math.abs(t.amount),0); async function save(e:React.FormEvent){e.preventDefault();const value=Number(amount);if(value<=0||!desc.trim())return setError("Заполни сумму и назначение");try{const result=await api.addTransaction({amount:-value,desc:desc.trim(),dateStr:toDDMMYYYY(new Date())});await refresh();setAmount("");setDesc("");showToast(`Трата добавлена в «${result.cat}»`)}catch(err){setError(err instanceof Error?err.message:"Не удалось сохранить")}} return <main><div className="max-w-[900px] mx-auto px-4 pt-5"><h1 className="font-display text-2xl font-bold">Расход</h1><section className="grid grid-cols-2 gap-3"><div className="rounded-2xl p-4" style={{background:"var(--hover)",border:"1px solid var(--border)"}}>Доход с {state.currentWeek.startDate}<br/><b>{state.currentWeek.income == null ? "не задан" : fmt(state.currentWeek.income)}</b></div><div className="rounded-2xl p-4" style={{background:"var(--hover)",border:"1px solid var(--border)"}}>Потрачено с {state.currentWeek.startDate}<br/><b>{fmt(-spent)}</b></div></section><form onSubmit={save} className="rounded-2xl p-4 mt-4" style={{background:"var(--hover)",border:"1px solid var(--border)"}}><b>Добавить расход</b><label className="block text-sm mt-3">Сколько потрачено<input aria-label="Сколько потрачено" type="number" value={amount} onChange={e=>setAmount(e.target.value)} className="block w-full mt-1 p-2"/></label><label className="block text-sm mt-3">На что<input aria-label="На что" value={desc} onChange={e=>setDesc(e.target.value)} className="block w-full mt-1 p-2"/></label>{error&&<p className="text-red-500 text-sm">{error}</p>}<button className="mt-3 px-4 py-2 rounded-xl" style={{background:"var(--accent-blue)",color:"#fff"}}>Добавить расход</button></form><p className="text-xs mt-3" style={{color:"var(--muted)"}}>Категория определяется по правилам; расход появится в соответствующем конверте ниже.</p></div><EnvelopesTab state={state} refresh={refresh} showToast={showToast}/></main> }
